//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowernApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowernApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm sound.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string AppBarInfo {
            get {
                return ResourceManager.GetString("AppBarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable connectivity.
        /// </summary>
        public static string AppBarOffline {
            get {
                return ResourceManager.GetString("AppBarOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Benjamin Sautermeister.
        /// </summary>
        public static string ApplicationAuthor {
            get {
                return ResourceManager.GetString("ApplicationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fastest powernapping app for Windows Phone with voice commands..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powernAPP.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold the Windows-Button of you phone until the voice input dialog pops up..
        /// </summary>
        public static string Commands1Message {
            get {
                return ResourceManager.GetString("Commands1Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Activate voice input.
        /// </summary>
        public static string Commands1Title {
            get {
                return ResourceManager.GetString("Commands1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot; ...for 20 minutes. &quot;.
        /// </summary>
        public static string Commands2Bullet1 {
            get {
                return ResourceManager.GetString("Commands2Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot; ...cancel nap. &quot;.
        /// </summary>
        public static string Commands2Bullet2 {
            get {
                return ResourceManager.GetString("Commands2Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot; ...when is my alarm set for? &quot;.
        /// </summary>
        public static string Commands2Bullet3 {
            get {
                return ResourceManager.GetString("Commands2Bullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot; ...what is the remaining time? &quot;.
        /// </summary>
        public static string Commands2Bullet4 {
            get {
                return ResourceManager.GetString("Commands2Bullet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot; ...give me 5 more minutes. &quot;.
        /// </summary>
        public static string Commands2Bullet5 {
            get {
                return ResourceManager.GetString("Commands2Bullet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        public static string Commands2Message1 {
            get {
                return ResourceManager.GetString("Commands2Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &quot;Power Nap...&quot;  .
        /// </summary>
        public static string Commands2Message2 {
            get {
                return ResourceManager.GetString("Commands2Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followed by your request. Some examples:.
        /// </summary>
        public static string Commands2Message3 {
            get {
                return ResourceManager.GetString("Commands2Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Speak.
        /// </summary>
        public static string Commands2Title {
            get {
                return ResourceManager.GetString("Commands2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powernAPP takes care of the rest....
        /// </summary>
        public static string Commands3Message {
            get {
                return ResourceManager.GetString("Commands3Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Enjoy your nap.
        /// </summary>
        public static string Commands3Title {
            get {
                return ResourceManager.GetString("Commands3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands.
        /// </summary>
        public static string CommandsHeader {
            get {
                return ResourceManager.GetString("CommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application supports Windows Phone voice commands. Follow these simple steps to take you well-deserved nap even faster:.
        /// </summary>
        public static string CommandsIntro {
            get {
                return ResourceManager.GetString("CommandsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t get disturbed. Disable the phones connectivity!.
        /// </summary>
        public static string ConnectivityHint {
            get {
                return ResourceManager.GetString("ConnectivityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBodyText {
            get {
                return ResourceManager.GetString("FeedbackBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps@bsautermeister.de.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate powernAPP.
        ///
        ///Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string FeedbackMessageText {
            get {
                return ResourceManager.GetString("FeedbackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNoText {
            get {
                return ResourceManager.GetString("FeedbackNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powernAPP Customer Feedback .
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYesText {
            get {
                return ResourceManager.GetString("FeedbackYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more apps.
        /// </summary>
        public static string MoreApps {
            get {
                return ResourceManager.GetString("MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep a regular nap schedule. Prime napping time falls in the middle of the day..
        /// </summary>
        public static string NappingTipsConsistentMessage {
            get {
                return ResourceManager.GetString("NappingTipsConsistentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be consistent.
        /// </summary>
        public static string NappingTipsConsistentTitle {
            get {
                return ResourceManager.GetString("NappingTipsConsistentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nap in a dark room or wear an eye mask. Blocking out light helps you fall asleep faster..
        /// </summary>
        public static string NappingTipsDarknessMessage {
            get {
                return ResourceManager.GetString("NappingTipsDarknessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer darkness.
        /// </summary>
        public static string NappingTipsDarknessTitle {
            get {
                return ResourceManager.GetString("NappingTipsDarknessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable your phones connectivity and search for silent places..
        /// </summary>
        public static string NappingTipsDisturbedMessage {
            get {
                return ResourceManager.GetString("NappingTipsDisturbedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t get disturbed.
        /// </summary>
        public static string NappingTipsDisturbedTitle {
            get {
                return ResourceManager.GetString("NappingTipsDisturbedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to napping tips.
        /// </summary>
        public static string NappingTipsHeader {
            get {
                return ResourceManager.GetString("NappingTipsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research has found that napping regularly may reduce stress and even decrease your risk of heart disease. To get the most out of a power snooze, follow these quick and simple tips:.
        /// </summary>
        public static string NappingTipsIntro {
            get {
                return ResourceManager.GetString("NappingTipsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your alarm for about 30 minutes or less if you don&apos;t want to wake up groggy. Because you should wake up before the occurrence of deep sleep..
        /// </summary>
        public static string NappingTipsQuickMessage {
            get {
                return ResourceManager.GetString("NappingTipsQuickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make it quick.
        /// </summary>
        public static string NappingTipsQuickTitle {
            get {
                return ResourceManager.GetString("NappingTipsQuickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash a blanket nearby to put over you because your body temperature drops while you snooze..
        /// </summary>
        public static string NappingTipsWarmMessage {
            get {
                return ResourceManager.GetString("NappingTipsWarmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay warm.
        /// </summary>
        public static string NappingTipsWarmTitle {
            get {
                return ResourceManager.GetString("NappingTipsWarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy info.
        /// </summary>
        public static string PrivacyInfo {
            get {
                return ResourceManager.GetString("PrivacyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string RatingMessage10Text {
            get {
                return ResourceManager.GetString("RatingMessage10Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessage5Text {
            get {
                return ResourceManager.GetString("RatingMessage5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNoText {
            get {
                return ResourceManager.GetString("RatingNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying powernAPP?.
        /// </summary>
        public static string RatingTitleText {
            get {
                return ResourceManager.GetString("RatingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYesText {
            get {
                return ResourceManager.GetString("RatingYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm is already set..
        /// </summary>
        public static string SpeakAlarmAlreadySet {
            get {
                return ResourceManager.GetString("SpeakAlarmAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm is set for {0}..
        /// </summary>
        public static string SpeakAlarmSetFor {
            get {
                return ResourceManager.GetString("SpeakAlarmSetFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm was not set..
        /// </summary>
        public static string SpeakNoAlarmSet {
            get {
                return ResourceManager.GetString("SpeakNoAlarmSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a nice {0} minutes nap..
        /// </summary>
        public static string SpeakStartNap {
            get {
                return ResourceManager.GetString("SpeakStartNap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm is now off. Hope you feel more energized..
        /// </summary>
        public static string SpeakStopNap {
            get {
                return ResourceManager.GetString("SpeakStopNap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} minutes left..
        /// </summary>
        public static string SpeakTimeLeft {
            get {
                return ResourceManager.GetString("SpeakTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you have {0} minutes left..
        /// </summary>
        public static string SpeakTimeShifted {
            get {
                return ResourceManager.GetString("SpeakTimeShifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support and feedback.
        /// </summary>
        public static string SupportAndFeedback {
            get {
                return ResourceManager.GetString("SupportAndFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        public static string VibrationEnabled {
            get {
                return ResourceManager.GetString("VibrationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice commands.
        /// </summary>
        public static string VoiceCommands {
            get {
                return ResourceManager.GetString("VoiceCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string VoiceLanguage {
            get {
                return ResourceManager.GetString("VoiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string VoiceStatus {
            get {
                return ResourceManager.GetString("VoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supported.
        /// </summary>
        public static string VoiceSupported {
            get {
                return ResourceManager.GetString("VoiceSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not supported.
        /// </summary>
        public static string VoiceUnsupported {
            get {
                return ResourceManager.GetString("VoiceUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your installed language package is not supported  in the current version of this application. Supported languages for voice commands are English (en-US, en-GB) and German (de-DE). Please check your phone settings..
        /// </summary>
        public static string VoiceUnsupportedMessage {
            get {
                return ResourceManager.GetString("VoiceUnsupportedMessage", resourceCulture);
            }
        }
    }
}
