//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowernApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowernApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about ähnelt.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm sound ähnelt.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake up! Hope you feel more energized now... ähnelt.
        /// </summary>
        public static string AlertDialogMessage {
            get {
                return ResourceManager.GetString("AlertDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die info ähnelt.
        /// </summary>
        public static string AppBarInfo {
            get {
                return ResourceManager.GetString("AppBarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die disable connectivity ähnelt.
        /// </summary>
        public static string AppBarOffline {
            get {
                return ResourceManager.GetString("AppBarOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enable connectivity ähnelt.
        /// </summary>
        public static string AppBarOnline {
            get {
                return ResourceManager.GetString("AppBarOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by Benjamin Sautermeister ähnelt.
        /// </summary>
        public static string ApplicationAuthor {
            get {
                return ResourceManager.GetString("ApplicationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The fastest power napping app for Windows Phone with voice commands. ähnelt.
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die powernAPP ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.5 ähnelt.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press and hold the Windows-Button of you phone until the voice input dialog pops up. ähnelt.
        /// </summary>
        public static string Commands1Message {
            get {
                return ResourceManager.GetString("Commands1Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Activate voice input ähnelt.
        /// </summary>
        public static string Commands1Title {
            get {
                return ResourceManager.GetString("Commands1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - &quot; ...for 20 minutes. &quot; ähnelt.
        /// </summary>
        public static string Commands2Bullet1 {
            get {
                return ResourceManager.GetString("Commands2Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - &quot; ...for 1 hour and 30 minutes. &quot; ähnelt.
        /// </summary>
        public static string Commands2Bullet1b {
            get {
                return ResourceManager.GetString("Commands2Bullet1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string Commands2Bullet1c {
            get {
                return ResourceManager.GetString("Commands2Bullet1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - &quot; ...cancel nap. &quot; ähnelt.
        /// </summary>
        public static string Commands2Bullet2 {
            get {
                return ResourceManager.GetString("Commands2Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - &quot; ...when is my alarm set for? &quot; ähnelt.
        /// </summary>
        public static string Commands2Bullet3 {
            get {
                return ResourceManager.GetString("Commands2Bullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - &quot; ...what is the remaining time? &quot; ähnelt.
        /// </summary>
        public static string Commands2Bullet4 {
            get {
                return ResourceManager.GetString("Commands2Bullet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - &quot; ...give me 5 more minutes. &quot; ähnelt.
        /// </summary>
        public static string Commands2Bullet5 {
            get {
                return ResourceManager.GetString("Commands2Bullet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Say ähnelt.
        /// </summary>
        public static string Commands2Message1 {
            get {
                return ResourceManager.GetString("Commands2Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  &quot;Power Nap...&quot;   ähnelt.
        /// </summary>
        public static string Commands2Message2 {
            get {
                return ResourceManager.GetString("Commands2Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die followed by your request. Some examples: ähnelt.
        /// </summary>
        public static string Commands2Message3 {
            get {
                return ResourceManager.GetString("Commands2Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. Speak ähnelt.
        /// </summary>
        public static string Commands2Title {
            get {
                return ResourceManager.GetString("Commands2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die powernAPP takes care of the rest... ähnelt.
        /// </summary>
        public static string Commands3Message {
            get {
                return ResourceManager.GetString("Commands3Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3. Enjoy your nap ähnelt.
        /// </summary>
        public static string Commands3Title {
            get {
                return ResourceManager.GetString("Commands3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die commands ähnelt.
        /// </summary>
        public static string CommandsHeader {
            get {
                return ResourceManager.GetString("CommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This application supports Windows Phone voice commands. Follow these simple steps to take you well-deserved nap even faster: ähnelt.
        /// </summary>
        public static string CommandsIntro {
            get {
                return ResourceManager.GetString("CommandsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t get disturbed. Disable the phones connectivity! ähnelt.
        /// </summary>
        public static string ConnectivityHint {
            get {
                return ResourceManager.GetString("ConnectivityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contributors ähnelt.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///--------------------------------- ähnelt.
        /// </summary>
        public static string FeedbackBodyText {
            get {
                return ResourceManager.GetString("FeedbackBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die apps@bsautermeister.de ähnelt.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry to hear you didn&apos;t want to rate powernAPP.
        ///
        ///Tell us about your experience or suggest how we can make it even better. ähnelt.
        /// </summary>
        public static string FeedbackMessageText {
            get {
                return ResourceManager.GetString("FeedbackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no thanks ähnelt.
        /// </summary>
        public static string FeedbackNoText {
            get {
                return ResourceManager.GetString("FeedbackNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die powernAPP Customer Feedback  ähnelt.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can we make it better? ähnelt.
        /// </summary>
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die give feedback ähnelt.
        /// </summary>
        public static string FeedbackYesText {
            get {
                return ResourceManager.GetString("FeedbackYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die information ähnelt.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more apps ähnelt.
        /// </summary>
        public static string MoreApps {
            get {
                return ResourceManager.GetString("MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep a regular nap schedule. Prime napping time falls in the middle of the day. ähnelt.
        /// </summary>
        public static string NappingTipsConsistentMessage {
            get {
                return ResourceManager.GetString("NappingTipsConsistentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Be consistent ähnelt.
        /// </summary>
        public static string NappingTipsConsistentTitle {
            get {
                return ResourceManager.GetString("NappingTipsConsistentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nap in a dark room or wear an eye mask. Blocking out light helps you fall asleep faster. ähnelt.
        /// </summary>
        public static string NappingTipsDarknessMessage {
            get {
                return ResourceManager.GetString("NappingTipsDarknessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prefer darkness ähnelt.
        /// </summary>
        public static string NappingTipsDarknessTitle {
            get {
                return ResourceManager.GetString("NappingTipsDarknessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable your phones connectivity and search for silent places. ähnelt.
        /// </summary>
        public static string NappingTipsDisturbedMessage {
            get {
                return ResourceManager.GetString("NappingTipsDisturbedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t get disturbed ähnelt.
        /// </summary>
        public static string NappingTipsDisturbedTitle {
            get {
                return ResourceManager.GetString("NappingTipsDisturbedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die napping tips ähnelt.
        /// </summary>
        public static string NappingTipsHeader {
            get {
                return ResourceManager.GetString("NappingTipsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Research has found that napping regularly may reduce stress and even decrease your risk of heart disease. To get the most out of a power snooze, follow these quick and simple tips: ähnelt.
        /// </summary>
        public static string NappingTipsIntro {
            get {
                return ResourceManager.GetString("NappingTipsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set your alarm for about 30 minutes or less if you don&apos;t want to wake up groggy. Because you should wake up before the occurrence of deep sleep. ähnelt.
        /// </summary>
        public static string NappingTipsQuickMessage {
            get {
                return ResourceManager.GetString("NappingTipsQuickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make it quick ähnelt.
        /// </summary>
        public static string NappingTipsQuickTitle {
            get {
                return ResourceManager.GetString("NappingTipsQuickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stash a blanket nearby to put over you because your body temperature drops while you snooze. ähnelt.
        /// </summary>
        public static string NappingTipsWarmMessage {
            get {
                return ResourceManager.GetString("NappingTipsWarmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stay warm ähnelt.
        /// </summary>
        public static string NappingTipsWarmTitle {
            get {
                return ResourceManager.GetString("NappingTipsWarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die privacy info ähnelt.
        /// </summary>
        public static string PrivacyInfo {
            get {
                return ResourceManager.GetString("PrivacyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rate and review ähnelt.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation? ähnelt.
        /// </summary>
        public static string RatingMessage10Text {
            get {
                return ResourceManager.GetString("RatingMessage10Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We&apos;d love you to rate our app 5 stars.
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better! ähnelt.
        /// </summary>
        public static string RatingMessage5Text {
            get {
                return ResourceManager.GetString("RatingMessage5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no thanks ähnelt.
        /// </summary>
        public static string RatingNoText {
            get {
                return ResourceManager.GetString("RatingNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enjoying powernAPP? ähnelt.
        /// </summary>
        public static string RatingTitleText {
            get {
                return ResourceManager.GetString("RatingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rate 5 stars ähnelt.
        /// </summary>
        public static string RatingYesText {
            get {
                return ResourceManager.GetString("RatingYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm is already set. ähnelt.
        /// </summary>
        public static string SpeakAlarmAlreadySet {
            get {
                return ResourceManager.GetString("SpeakAlarmAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm is set for {0}. ähnelt.
        /// </summary>
        public static string SpeakAlarmSetFor {
            get {
                return ResourceManager.GetString("SpeakAlarmSetFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm was not set. ähnelt.
        /// </summary>
        public static string SpeakNoAlarmSet {
            get {
                return ResourceManager.GetString("SpeakNoAlarmSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have a nice {0} minutes nap. ähnelt.
        /// </summary>
        public static string SpeakStartNap1 {
            get {
                return ResourceManager.GetString("SpeakStartNap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have a nice {0} minutes sleep. ähnelt.
        /// </summary>
        public static string SpeakStartNap2 {
            get {
                return ResourceManager.GetString("SpeakStartNap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm is now off. Hope you feel more energized. ähnelt.
        /// </summary>
        public static string SpeakStopNap1 {
            get {
                return ResourceManager.GetString("SpeakStopNap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm is now off. Hope you had a good sleep. ähnelt.
        /// </summary>
        public static string SpeakStopNap2 {
            get {
                return ResourceManager.GetString("SpeakStopNap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have {0} minutes left. ähnelt.
        /// </summary>
        public static string SpeakTimeLeft {
            get {
                return ResourceManager.GetString("SpeakTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Now you have about {0} minutes left. ähnelt.
        /// </summary>
        public static string SpeakTimeShifted {
            get {
                return ResourceManager.GetString("SpeakTimeShifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die support and feedback ähnelt.
        /// </summary>
        public static string SupportAndFeedback {
            get {
                return ResourceManager.GetString("SupportAndFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suppress lock screen ähnelt.
        /// </summary>
        public static string SuppressLockScreen {
            get {
                return ResourceManager.GetString("SuppressLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vibration ähnelt.
        /// </summary>
        public static string VibrationEnabled {
            get {
                return ResourceManager.GetString("VibrationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voice commands ähnelt.
        /// </summary>
        public static string VoiceCommands {
            get {
                return ResourceManager.GetString("VoiceCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play audio confirmations ähnelt.
        /// </summary>
        public static string VoiceFeedback {
            get {
                return ResourceManager.GetString("VoiceFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string VoiceLanguage {
            get {
                return ResourceManager.GetString("VoiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string VoiceStatus {
            get {
                return ResourceManager.GetString("VoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die supported ähnelt.
        /// </summary>
        public static string VoiceSupported {
            get {
                return ResourceManager.GetString("VoiceSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not supported ähnelt.
        /// </summary>
        public static string VoiceUnsupported {
            get {
                return ResourceManager.GetString("VoiceUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your installed language package is not supported  in the current version of this application. Supported languages for voice commands are English (en-US, en-GB, en-IN), French (fr-FR), Portuguese (pt-PT, pt-BR), Indonesian (id-ID) and German (de-DE). Please check your phone settings.
        ///You want to help with the translation to support your language in the next version? Just contact me! ähnelt.
        /// </summary>
        public static string VoiceUnsupportedMessage {
            get {
                return ResourceManager.GetString("VoiceUnsupportedMessage", resourceCulture);
            }
        }
    }
}
